version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 10
    labels:
      - branch:main

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: release-v1.1.x
    open-pull-requests-limit: 10
    labels:
      - branch:release-v1.1.x

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - branch:main

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: release-v1.1.x
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - branch:release-v1.1.x
