[versions]
nmcp = "1.3.0"
problem4j-core = "1.2.6"
problem4j-jackson = "1.2.7"
problem4j-jackson3 = "1.2.7"
spotless = "8.1.0"
spring-boot = "4.0.0"

[plugins]
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# direct versions
problem4j-core = { module = "io.github.malczuuu.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson = { module = "io.github.malczuuu.problem4j:problem4j-jackson", version.ref = "problem4j-jackson" }
problem4j-jackson3 = { module = "io.github.malczuuu.problem4j:problem4j-jackson3", version.ref = "problem4j-jackson3" }

# versions managed by spring-boot-dependencies
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-jackson = { module = "org.springframework.boot:spring-boot-jackson" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-validation" }
spring-boot-web-server = { module = "org.springframework.boot:spring-boot-web-server" }
spring-boot-webflux = { module = "org.springframework.boot:spring-boot-webflux" }
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-webmvc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-web = { module = "org.springframework:spring-web" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson3-dataformat-xml = { module = "tools.jackson.dataformat:jackson-dataformat-xml" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
